apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    app: webapp
spec:
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2